---
- name: Testing Graylog modules
  hosts: localhost
  tasks:

    - name: Validate pipeline rule
      graylog_pipelines:
        action: parse_rule
        endpoint: "{{ endpoint }}"
        graylog_user: "{{ graylog_user }}"
        graylog_password: "{{ graylog_password }}"
        source: |
          rule "test_rule_domain_threat_intel"
          when
             has_field("dns_query")
          then
             let dns_query_intel = threat_intel_lookup_domain(to_string($message.dns_query), "dns_query");
             set_fields(dns_query_intel);
          end
      register: pipeline_rule
