---
- name: Testing Graylog modules
  hosts: localhost
  tasks:

    - name: Create Graylog role
      graylog_roles:
        action: create
        endpoint: "{{ endpoint }}"
        graylog_user: "admin"
        graylog_password: "{{ graylog_password }}"
        name: "ansible_role"
        description: "Ansible test role"
        permissions:
          - "dashboards:read"
        read_only: "true"

    - name: Update Graylog role
      graylog_roles:
        action: update
        endpoint: "{{ endpoint }}"
        graylog_user: "admin"
        graylog_password: "{{ graylog_password }}"
        name: "ansible_role"
        description: "Ansible test role update"
        permissions:
          - "dashboards:read"
        read_only: "true"

    - name: List Graylog roles
      graylog_roles:
        endpoint: "{{ endpoint }}"
        graylog_user: "admin"
        graylog_password: "{{ graylog_password }}"
      register: graylog_roles

    - name: Print roles
      debug:
        msg: "{{ graylog_roles }}"

    - name: Create Graylog user
      graylog_users:
        action: create
        endpoint: "{{ endpoint }}"
        graylog_user: "admin"
        graylog_password: "{{ graylog_password }}"
        username: "ansible_user"
        full_name: "Ansible User"
        password: "{{ password }}"
        email: "old-email@aol.com"
        roles:
          - "ansible_role"

    - name: Update Graylog user
      graylog_users:
        action: update
        endpoint: "{{ endpoint }}"
        graylog_user: "admin"
        graylog_password: "{{ graylog_password }}"
        username: "ansible_user"
        email: "new-email@aol.com"

    - name: List Graylog users
      graylog_users:
        endpoint: "{{ endpoint }}"
        graylog_user: "admin"
        graylog_password: "{{ graylog_password }}"
      register: graylog_users

    - name: Print users
      debug:
        msg: "{{ graylog_users }}"

    - name: Remove user
      graylog_users:
        action: delete
        endpoint: "{{ endpoint }}"
        graylog_user: "admin"
        graylog_password: "{{ graylog_password }}"
        username: "ansible_user"

    - name: Remove role
      graylog_roles:
        action: delete
        endpoint: "{{ endpoint }}"
        graylog_user: "admin"
        graylog_password: "{{ graylog_password }}"
        name: "ansible_role"

    - name: List streams
      graylog_streams:
        endpoint: "{{ endpoint }}"
        graylog_user: "admin"
        graylog_password: "{{ graylog_password }}"

    - name: Create stream
      graylog_streams:
        action: create
        endpoint: "{{ endpoint }}"
        graylog_user: "admin"
        graylog_password: "{{ graylog_password }}"
        title: "test_stream"
        description: "Windows and IIS logs"
        matching_type: "AND"
        remove_matches_from_default_stream: False
        rules:
          - {"field":"message","type":1,"value":"test_stream rule","inverted": false,"description":"test_stream rule"}

    - name: Get stream from stream name query
      graylog_streams:
        action: query_streams
        endpoint: "{{ endpoint }}"
        graylog_user: "admin"
        graylog_password: "{{ graylog_password }}"
        stream_name: "test_stream"
      register: stream

    - name:  List single stream by ID
      graylog_streams:
        endpoint: "{{ endpoint }}"
        graylog_user: "admin"
        graylog_password: "{{ graylog_password }}"
        stream_id: "{{ stream.json.id }}"

    - name: Update stream
      graylog_streams:
        action: update
        endpoint: "{{ endpoint }}"
        graylog_user: "admin"
        graylog_password: "{{ graylog_password }}"
        stream_id: "{{ stream.json.id }}"
        remove_matches_from_default_stream: True

    - name: Create stream rule
      graylog_streams:
        action: create_rule
        endpoint: "{{ endpoint }}"
        graylog_user: "admin"
        graylog_password: "{{ graylog_password }}"
        stream_id: "{{ stream.json.id }}"
        description: "Windows Security Logs"
        field: "winlogbeat_log_name"
        type: "1"
        value: "Security"
        inverted: False
    #
    # - name: Update stream rule
    #   graylog_streams:
    #     action: update_rule
    #     endpoint: "{{ endpoint }}"
    #     graylog_user: "admin"
    #     graylog_password: "{{ graylog_password }}"
    #     stream_id: "{{ stream.json.id }}"
    #     rule_id: "{{ rule.json.id }}"
    #     description: "Windows Security and Application Logs"
    #
    # - name: Delete stream rule
    #   graylog_streams:
    #     action: delete_rule
    #     endpoint: "{{ endpoint }}"
    #     graylog_user: "admin"
    #     graylog_password: "{{ graylog_password }}"
    #     stream_id: "{{ stream.json.id }}"
    #     rule_id: "{{ rule.json.id }}"
    #
    - name: Delete stream
      graylog_streams:
        action: delete
        endpoint: "{{ endpoint }}"
        graylog_user: "admin"
        graylog_password: "{{ graylog_password }}"
        stream_id: "{{ stream.json.id }}"
